### PR TITLE
change _addForBounds first argument to hash object

### PR DESCRIPTION
**Pull request by nguyenning**
After looking at it more I think this is the better fix for my IE 8 issue.

What happened was IE doesn't have support for Array.prototype.indexOf and somewhere in my code it added a shim for it.  

When addForBounds loops through the layerArray, "indexOf" was returned as one of the keys, then crashes out.

The better fix is to add as a hash object instead of an array on line 22 of `boundsawarelayergroup.js`.

In Leaflet source code for [LayerGroup](https://github.com/Leaflet/Leaflet/blob/master/src/layer/LayerGroup.js#L9), you can see that 

```
this._layers = {}; 
```

### CODE REVIEW

**Comment by brandoncopeland** [comment]
What if we changed the loop from a 'for..in' to a plain 'for' (`for (var i = 0, j = myArray.length; i < j; i++)`)? Does that also fix your issue?

**Comment by nguyenning** [comment]
Hmm I don't think so since `this._layers` is originally a JS hash object so calling `myArray.length` would return undefined.  I can confirm after lunch though.

**Comment by brandoncopeland** [comment]
Ok. I see. Thought we were only dealing with arrays. That is probably why I used 'for..in' to begin with.

**Comment by nguyenning** [comment]
Cool, can you bump the package.json version up and update npm?

**Comment by brandoncopeland** [comment]
@nguyenning version 1.2.2 is up

**Comment by nguyenning** [comment]
Not sure if it's cached but https://www.npmjs.org/package/leaflet-boundsawarelayergroup still says 1.2.1

**Pull request merged**
